### ISSUE TITLE
Reddit post

### ISSUE THREAD

**Issue by thetredev** [xdeb-org/xdeb#25]
I think we can push this whole thing a bit more at https://reddit.com/r/voidlinux. But since there are a couple issues with the 4th release, maybe it's best to release a new version before posting there.

**Comment by toluschr** [comment]
Before drafting a new release, a lot of bugs on master need to be (found and) worked on. I added a simple test system that should hopefully aid in the process. Feel free to suggest any packages with quirks that may require additional testing.

**Comment by thetredev** [comment]
I can't think of any sadly. Can you narrow the search down? Like, do we want things like Flatpak or Steam to work via xdeb or just those packages that aren't (directly) part of the Void ecosystem?

**Comment by toluschr** [comment]
@thetredev I released a new version a couple of days ago.

Reading some of the posts on r/voidlinux, it seems many people just ignored the critical error messages and broke their system as a result. They added an automatic moderator message that `xdeb` should not be used.

![Moderator message on r/voidlinux regarding xdeb](https://github.com/xdeb-org/xdeb/assets/44272603/0dbc0223-2e54-4384-94f0-38abe88c0ea5)

I don't think you should post there.

To combat this in the future, in case of an error, `xdeb` doesn't print installation instructions anymore. Additionally, automatic conflict resolution should probably be enabled by default.

What do you think?

**Comment by thetredev** [comment]
Yeah, I heard the same from the Void maintainers as well. No Reddit post then :D 

I agree with your proposals/changes.

**Comment by thetredev** [comment]
Closing this one because I guess it's with a15f5ba.
