### ISSUE TITLE
readme: --revision is not an alternative for -r

### ISSUE THREAD

**Issue by thetredev** [xdeb-org/xdeb#26]
https://github.com/xdeb-org/xdeb/blob/master/readme.md?plain=1#L48 states that `--rev=` and `--revision=` are alternatives for `-r`. But `-r` is "Clean repodata (Use when rebuilding a package)".

I think `--rev`/`--revision` and `-r` are completely different things. By the way, is `-r` actually used? Couldn't find it in the script. Maybe I'm blind tho :D

**Comment by toluschr** [comment]
The wording is confusing here. It means either (-r) remove the package entirely or (--revision) keep the old package and bump the revision.

**Comment by toluschr** [comment]
-r was a hacky way to deal with this, before --revision was introdced. It is not ideal, but I don't think existing behavior should be changed or removed either.

**Comment by thetredev** [comment]
Ahhh gotcha. Closing.
