### ISSUE TITLE
[BUG] Kodi not installing to correct directory?

### ISSUE THREAD

**Issue by ACR-Jeff** [xdeb-org/xdeb#28]
# Information

* options: -Sedf<br>
  *output of* `env | grep XDEB`
* version: 20240610<br>
  *either version, or commit id. ie: [9f69cf3, 1.2]*
* cmdline: xdeb -Sedf kodi_20.1+dfsg-1_amd64.deb<br>
  *command used to convert the package, including* `XDEB_PKGROOT`
* [ ] #29
* [ ] installation failed

# Package

* name: kodi_20.1+dfsg-1_amd64.deb<br>
  *name of the package*
* download: http://http.us.debian.org/debian/pool/main/k/kodi/kodi_20.1+dfsg-1_amd64.deb<br>
  *link to .deb file*

# Script output
<details>

</details>

# Describe the issue
Everything seemed to install, Until I executed Kodi via terminal
Error: /usr/lib/x86_64-linux-gnu/kodi/kodi.bin not found

**Comment by toluschr** [comment]
You need to install the following packages using xdeb and execute kodi using `LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/lib" kodi`
- [kodi](http://ftp.de.debian.org/debian/pool/main/k/kodi/kodi_20.1+dfsg-1_amd64.deb)
- [kodi-bin](http://ftp.de.debian.org/debian/pool/main/k/kodi/kodi-bin_20.1+dfsg-1_amd64.deb)
- [liblirc-client0](http://ftp.de.debian.org/debian/pool/main/l/lirc/liblirc-client0_0.10.1-7.2_amd64.deb)
- [libnfs13](http://ftp.de.debian.org/debian/pool/main/libn/libnfs/libnfs13_4.0.0-1_amd64.deb)
- [libudfread0](http://ftp.de.debian.org/debian/pool/main/libu/libudfread/libudfread0_1.1.2-1_amd64.deb)
- [libcrossguid0](http://ftp.de.debian.org/debian/pool/main/c/crossguid/libcrossguid0_0.0+git200150803-6_amd64.deb)
- [libcurl3-gnutls](http://ftp.de.debian.org/debian/pool/main/c/curl/libcurl3-gnutls_7.88.1-10+deb12u5_amd64.deb)
- [libavcodec59](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libavcodec59_5.1.4-0+deb12u1_amd64.deb)
- [libavfilter8](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libavfilter8_5.1.4-0+deb12u1_amd64.deb)
- [libavformat59](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libavformat59_5.1.4-0+deb12u1_amd64.deb)
- [libavutil57](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libavutil57_5.1.4-0+deb12u1_amd64.deb)
- [libswscale6](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libswscale6_5.1.4-0+deb12u1_amd64.deb)
- [libswresample4](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libswresample4_5.1.4-0+deb12u1_amd64.deb)
- [libpostproc56](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libpostproc56_5.1.4-0+deb12u1_amd64.deb)
- [libkissfft-float131](http://ftp.de.debian.org/debian/pool/main/k/kissfft/libkissfft-float131_131.1.0-3_amd64.deb)
- [libpcre3](http://ftp.de.debian.org/debian/pool/main/p/pcre3/libpcre3_8.39-15_amd64.deb)
- [libspdlog1.10](http://ftp.de.debian.org/debian/pool/main/s/spdlog/libspdlog1.10_1.10.0+ds-0.4_amd64.deb)
- [libtinyxml2.6.2v5](http://ftp.de.debian.org/debian/pool/main/t/tinyxml/libtinyxml2.6.2v5_2.6.2-6+deb12u1_amd64.deb)
- [libwayland-client++1](http://ftp.de.debian.org/debian/pool/main/w/waylandpp/libwayland-client++1_1.0.0-4_amd64.deb)
- [libwayland-cursor++1](http://ftp.de.debian.org/debian/pool/main/w/waylandpp/libwayland-cursor++1_1.0.0-4_amd64.deb)
- [libwayland-egl++1](http://ftp.de.debian.org/debian/pool/main/w/waylandpp/libwayland-egl++1_1.0.0-4_amd64.deb)
- [libshairplay0](http://ftp.de.debian.org/debian/pool/main/s/shairplay/libshairplay0_0.9.0~git20180824.096b61a+dfsg1-3_amd64.deb)
- [libldap-2.5-0](http://ftp.de.debian.org/debian/pool/main/o/openldap/libldap-2.5-0_2.5.13+dfsg-5_amd64.deb)
- [libdav1d6-debian](http://ftp.de.debian.org/debian/pool/main/d/dav1d/libdav1d6_1.0.0-2_amd64.deb)
- [libzvbi0](http://ftp.de.debian.org/debian/pool/main/z/zvbi/libzvbi0_0.2.41-1_amd64.deb)
- [libjxl0.7](http://ftp.de.debian.org/debian/pool/main/j/jpeg-xl/libjxl0.7_0.7.0-10_amd64.deb)
- [libshine3](http://ftp.de.debian.org/debian/pool/main/s/shine/libshine3_3.1.1-2_amd64.deb)
- [libx264-164](http://ftp.de.debian.org/debian/pool/main/x/x264/libx264-164_0.164.3095+gitbaee400-3_amd64.deb)
- [libmfx1](http://ftp.de.debian.org/debian/pool/main/i/intel-mediasdk/libmfx1_22.5.4-1_amd64.deb)
- [libpocketsphinx3](http://ftp.de.debian.org/debian/pool/main/p/pocketsphinx/libpocketsphinx3_0.8+5prealpha+1-15_amd64.deb)
- [libsphinxbase3](http://ftp.de.debian.org/debian/pool/main/s/sphinxbase/libsphinxbase3_0.8+5prealpha+1-16_amd64.deb)
- [libplacebo208](http://ftp.de.debian.org/debian/pool/main/libp/libplacebo/libplacebo208_4.208.0-3_amd64.deb)
- [libsrt1.5-gnutls](http://ftp.de.debian.org/debian/pool/main/s/srt/libsrt1.5-gnutls_1.5.1-1_amd64.deb)
- [libssh-gcrypt-4](http://ftp.de.debian.org/debian/pool/main/libs/libssh/libssh-gcrypt-4_0.10.6-0+deb12u1_amd64.deb)
- [libsasl2-2](http://ftp.de.debian.org/debian/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.28+dfsg-10_amd64.deb)
- [libhwy1](http://ftp.de.debian.org/debian/pool/main/h/highway/libhwy1_1.0.3-3+deb12u1_amd64.deb)
- [kodi-data](http://ftp.de.debian.org/debian/pool/main/k/kodi/kodi-data_20.1+dfsg-1_all.deb)

**Comment by ACR-Jeff** [comment]
> You need to install the following packages using xdeb and execute kodi using `LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/lib" kodi`
> 
>     * [kodi](http://ftp.de.debian.org/debian/pool/main/k/kodi/kodi_20.1+dfsg-1_amd64.deb)
> 
>     * [kodi-bin](http://ftp.de.debian.org/debian/pool/main/k/kodi/kodi-bin_20.1+dfsg-1_amd64.deb)
> 
>     * [liblirc-client0](http://ftp.de.debian.org/debian/pool/main/l/lirc/liblirc-client0_0.10.1-7.2_amd64.deb)
> 
>     * [libnfs13](http://ftp.de.debian.org/debian/pool/main/libn/libnfs/libnfs13_4.0.0-1_amd64.deb)
> 
>     * [libudfread0](http://ftp.de.debian.org/debian/pool/main/libu/libudfread/libudfread0_1.1.2-1_amd64.deb)
> 
>     * [libcrossguid0](http://ftp.de.debian.org/debian/pool/main/c/crossguid/libcrossguid0_0.0+git200150803-6_amd64.deb)
> 
>     * [libcurl3-gnutls](http://ftp.de.debian.org/debian/pool/main/c/curl/libcurl3-gnutls_7.88.1-10+deb12u5_amd64.deb)
> 
>     * [libavcodec59](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libavcodec59_5.1.4-0+deb12u1_amd64.deb)
> 
>     * [libavfilter8](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libavfilter8_5.1.4-0+deb12u1_amd64.deb)
> 
>     * [libavformat59](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libavformat59_5.1.4-0+deb12u1_amd64.deb)
> 
>     * [libavutil57](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libavutil57_5.1.4-0+deb12u1_amd64.deb)
> 
>     * [libswscale6](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libswscale6_5.1.4-0+deb12u1_amd64.deb)
> 
>     * [libswresample4](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libswresample4_5.1.4-0+deb12u1_amd64.deb)
> 
>     * [libpostproc56](http://ftp.de.debian.org/debian/pool/main/f/ffmpeg/libpostproc56_5.1.4-0+deb12u1_amd64.deb)
> 
>     * [libkissfft-float131](http://ftp.de.debian.org/debian/pool/main/k/kissfft/libkissfft-float131_131.1.0-3_amd64.deb)
> 
>     * [libpcre3](http://ftp.de.debian.org/debian/pool/main/p/pcre3/libpcre3_8.39-15_amd64.deb)
> 
>     * [libspdlog1.10](http://ftp.de.debian.org/debian/pool/main/s/spdlog/libspdlog1.10_1.10.0+ds-0.4_amd64.deb)
> 
>     * [libtinyxml2.6.2v5](http://ftp.de.debian.org/debian/pool/main/t/tinyxml/libtinyxml2.6.2v5_2.6.2-6+deb12u1_amd64.deb)
> 
>     * [libwayland-client++1](http://ftp.de.debian.org/debian/pool/main/w/waylandpp/libwayland-client++1_1.0.0-4_amd64.deb)
> 
>     * [libwayland-cursor++1](http://ftp.de.debian.org/debian/pool/main/w/waylandpp/libwayland-cursor++1_1.0.0-4_amd64.deb)
> 
>     * [libwayland-egl++1](http://ftp.de.debian.org/debian/pool/main/w/waylandpp/libwayland-egl++1_1.0.0-4_amd64.deb)
> 
>     * [libshairplay0](http://ftp.de.debian.org/debian/pool/main/s/shairplay/libshairplay0_0.9.0~git20180824.096b61a+dfsg1-3_amd64.deb)
> 
>     * [libldap-2.5-0](http://ftp.de.debian.org/debian/pool/main/o/openldap/libldap-2.5-0_2.5.13+dfsg-5_amd64.deb)
> 
>     * [libdav1d6-debian](http://ftp.de.debian.org/debian/pool/main/d/dav1d/libdav1d6_1.0.0-2_amd64.deb)
> 
>     * [libzvbi0](http://ftp.de.debian.org/debian/pool/main/z/zvbi/libzvbi0_0.2.41-1_amd64.deb)
> 
>     * [libjxl0.7](http://ftp.de.debian.org/debian/pool/main/j/jpeg-xl/libjxl0.7_0.7.0-10_amd64.deb)
> 
>     * [libshine3](http://ftp.de.debian.org/debian/pool/main/s/shine/libshine3_3.1.1-2_amd64.deb)
> 
>     * [libx264-164](http://ftp.de.debian.org/debian/pool/main/x/x264/libx264-164_0.164.3095+gitbaee400-3_amd64.deb)
> 
>     * [libmfx1](http://ftp.de.debian.org/debian/pool/main/i/intel-mediasdk/libmfx1_22.5.4-1_amd64.deb)
> 
>     * [libpocketsphinx3](http://ftp.de.debian.org/debian/pool/main/p/pocketsphinx/libpocketsphinx3_0.8+5prealpha+1-15_amd64.deb)
> 
>     * [libsphinxbase3](http://ftp.de.debian.org/debian/pool/main/s/sphinxbase/libsphinxbase3_0.8+5prealpha+1-16_amd64.deb)
> 
>     * [libplacebo208](http://ftp.de.debian.org/debian/pool/main/libp/libplacebo/libplacebo208_4.208.0-3_amd64.deb)
> 
>     * [libsrt1.5-gnutls](http://ftp.de.debian.org/debian/pool/main/s/srt/libsrt1.5-gnutls_1.5.1-1_amd64.deb)
> 
>     * [libssh-gcrypt-4](http://ftp.de.debian.org/debian/pool/main/libs/libssh/libssh-gcrypt-4_0.10.6-0+deb12u1_amd64.deb)
> 
>     * [libsasl2-2](http://ftp.de.debian.org/debian/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.28+dfsg-10_amd64.deb)
> 
>     * [libhwy1](http://ftp.de.debian.org/debian/pool/main/h/highway/libhwy1_1.0.3-3+deb12u1_amd64.deb)
> 
>     * [kodi-data](http://ftp.de.debian.org/debian/pool/main/k/kodi/kodi-data_20.1+dfsg-1_all.deb)

Thank you, I will attempt this within the next few days.

**Comment by ACR-Jeff** [comment]
Thank you for your information. I took the time to install everything on your list. Yet it still through a python error for shared libraries, I restored my system back to a timeshift, I may come back to it in the future and give it a go. But for now I am going to let it rest. Thank you again.
